version: '3'

services:
    bookstore-server:
        container_name: bookstore-server
        build: ./
        restart: unless-stopped
        ports:
          - 4000:4000
        volumes:
            - ./static:/usr/src/app/static
        env_file:
          - ./.env-docker
